name: Build and Release OnePlus Kernels

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:

jobs:
  build-kernel-op11:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OP11"
      soc: "kalama"
      branch: "oneplus/sm8550"
      manifest: "oneplus_11_b.xml"
      android_version: "android13"
      kernel_version: "5.15"
  build-kernel-op12:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: "OP12"
      soc: "pineapple"
      branch: "oneplus/sm8650"
      manifest: "oneplus_12_b.xml"
      android_version: "android14"
      kernel_version: "6.1"
